# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Python distributions to PyPI

on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-n-publish:
    name: "Build and publish package"
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python3
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          # Upgrade pip
          python -m pip install --upgrade pip
          # Install build deps
          python -m pip install setuptools wheel twine
      - name: "Build a binary wheel and a source tarball and uploads to PyPI"
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPIHAVERSINE_TOKEN }}